name = "UnitfulSystems"
uuid = "6db11e41-c221-4ba5-a210-07bd69f9cc83"
authors = ["Michael Reed"]
version = "0.1.0"

[deps]
UnitSystems = "3a241a3c-2137-41aa-af5e-1388e404ca09"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
UnitSystems = "0.2"
Unitful = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
